apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: vikram42/vikram-sit722-part2:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://library_db_ukuu_user:JK1UYU4Tyhlqd8A0swc5T8iatJXsfvX5@dpg-cr836vjqf0us73boeeg0-a.oregon-postgres.render.com/library_db_ukuu" 
